/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_slkk_opencvdemo_JniActivity */

#ifndef _Included_com_slkk_opencvdemo_JniActivity
#define _Included_com_slkk_opencvdemo_JniActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_slkk_opencvdemo_JniActivity
 * Method:    getEge
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_slkk_opencvdemo_JniActivity_getEge
  (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_com_slkk_opencvdemo_CaptureImageActivity_capImage
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
